accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user-register'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify-code'),
    path('login/', views.UserLoginView.as_view(), name='user-login'),
    path('logout/', views.UserLogoutView.as_view(), name='user-logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

bucket_urls = [
    path('', views.BucketHomeView.as_view(), name='bucket'),
    path('delete-object/<str:key>/', views.DeleteBucketObjectView.as_view(), name='delete-object-bucket'),
    path('download-object/<str:key>/', views.DownloadBucketObjectView.as_view(), name='download-object-bucket'),
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<slug:category_slug>/', views.HomeView.as_view(), name='category-filter'),
    path('bucket/', include(bucket_urls)),
    path('<slug:slug>/', views.ProductDetailView.as_view(), name='product-detail')
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('crate/', views.OrderCreateView.as_view(), name='order-create'),
    path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order-detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart-add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart-remove'),
    path('apply/<int:order_id>/' , views.ApplyCouponView.as_view(), name='apply-coupon')
]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-nav">
            <a class="nav-link active" href="{% url 'home:home' %}">Home</a>
            {% if request.user.is_authenticated %}
            <a class="nav-link active" href="{% url 'accounts:user-logout' %}">Logout</a>
            <a class="nav-link active" href="{% url 'orders:cart' %}">Cart {{ cart|length }}</a>#}
            {% else %}
            <a class="nav-link active" href="{% url 'accounts:user-register' %}">Register</a>
            <a class="nav-link active" href="{% url 'accounts:user-login' %}">Login</a>
            {% endif %}
<!--            {% if request.user.is_admin %}#}-->
<!--            <a class="nav-link active" href="{% url 'home:bucket' %}">Bucket</a>#}-->
<!--            {% endif %}#}-->


        </div>
    </div>
</nav>